version: '2'
services:
    planner-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/Planner/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=Planner
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
